apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dgoff-app
  name: dgoff-app
  namespace: dgoff-app
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: dgoff-app
