apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dgoff-app
  name: dgoff-app
  namespace: dgoff-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dgoff-app
  strategy: {}
  template:
    metadata:
      labels:
        app: dgoff-app
    spec:
      containers:
      - image: quay.io/redhatworkshops/bgd
        name: bgd
        resources: {}
